version: "3.7"

volumes:
  postgres_data:

services:

  backend:
    build: ./backend/
    container_name: notes_backend
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env
    restart: always

  postgres:
    image: postgres:15.3
    container_name: notes_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notes
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
